
import { BibleBook } from './types';

export const BIBLE_BOOKS: BibleBook[] = [
  // 舊約 (39卷)
  { id: 'GEN', name: '創世記', chapters: 50, testament: 'Old' },
  { id: 'EXO', name: '出埃及記', chapters: 40, testament: 'Old' },
  { id: 'LEV', name: '利未記', chapters: 27, testament: 'Old' },
  { id: 'NUM', name: '民數記', chapters: 36, testament: 'Old' },
  { id: 'DEU', name: '申命記', chapters: 34, testament: 'Old' },
  { id: 'JOS', name: '約書亞記', chapters: 24, testament: 'Old' },
  { id: 'JDG', name: '士師記', chapters: 21, testament: 'Old' },
  { id: 'RUT', name: '路得記', chapters: 4, testament: 'Old' },
  { id: '1SA', name: '撒母耳記上', chapters: 31, testament: 'Old' },
  { id: '2SA', name: '撒母耳記下', chapters: 24, testament: 'Old' },
  { id: '1KI', name: '列王紀上', chapters: 22, testament: 'Old' },
  { id: '2KI', name: '列王紀下', chapters: 25, testament: 'Old' },
  { id: '1CH', name: '歷代志上', chapters: 29, testament: 'Old' },
  { id: '2CH', name: '歷代志下', chapters: 36, testament: 'Old' },
  { id: 'EZR', name: '以斯拉記', chapters: 10, testament: 'Old' },
  { id: 'NEH', name: '尼希米記', chapters: 13, testament: 'Old' },
  { id: 'EST', name: '斯帖記', chapters: 10, testament: 'Old' },
  { id: 'JOB', name: '約伯記', chapters: 42, testament: 'Old' },
  { id: 'PSA', name: '詩篇', chapters: 150, testament: 'Old' },
  { id: 'PRO', name: '箴言', chapters: 31, testament: 'Old' },
  { id: 'ECC', name: '傳道書', chapters: 12, testament: 'Old' },
  { id: 'SNG', name: '雅歌', chapters: 8, testament: 'Old' },
  { id: 'ISA', name: '以賽亞書', chapters: 66, testament: 'Old' },
  { id: 'JER', name: '耶利米書', chapters: 52, testament: 'Old' },
  { id: 'LAM', name: '耶利米哀歌', chapters: 5, testament: 'Old' },
  { id: 'EZK', name: '以西結書', chapters: 48, testament: 'Old' },
  { id: 'DAN', name: '但以理書', chapters: 12, testament: 'Old' },
  { id: 'HOS', name: '何西阿書', chapters: 14, testament: 'Old' },
  { id: 'JOL', name: '約珥書', chapters: 3, testament: 'Old' },
  { id: 'AMO', name: '阿摩司書', chapters: 9, testament: 'Old' },
  { id: 'OBD', name: '俄巴底亞書', chapters: 1, testament: 'Old' },
  { id: 'JON', name: '約拿書', chapters: 4, testament: 'Old' },
  { id: 'MIC', name: '彌迦書', chapters: 7, testament: 'Old' },
  { id: 'NAH', name: '那鴻書', chapters: 3, testament: 'Old' },
  { id: 'HAB', name: '哈巴谷書', chapters: 3, testament: 'Old' },
  { id: 'ZEP', name: '西番雅書', chapters: 3, testament: 'Old' },
  { id: 'HAG', name: '哈該書', chapters: 2, testament: 'Old' },
  { id: 'ZEC', name: '撒迦利亞書', chapters: 14, testament: 'Old' },
  { id: 'MAL', name: '瑪拉基書', chapters: 4, testament: 'Old' },

  // 新約 (27卷)
  { id: 'MAT', name: '馬太福音', chapters: 28, testament: 'New' },
  { id: 'MRK', name: '馬可福音', chapters: 16, testament: 'New' },
  { id: 'LUK', name: '路加福音', chapters: 24, testament: 'New' },
  { id: 'JHN', name: '約翰福音', chapters: 21, testament: 'New' },
  { id: 'ACT', name: '使徒行傳', chapters: 28, testament: 'New' },
  { id: 'ROM', name: '羅馬書', chapters: 16, testament: 'New' },
  { id: '1CO', name: '哥林多前書', chapters: 16, testament: 'New' },
  { id: '2CO', name: '哥林多後書', chapters: 13, testament: 'New' },
  { id: 'GAL', name: '加拉太書', chapters: 6, testament: 'New' },
  { id: 'EPH', name: '以弗所書', chapters: 6, testament: 'New' },
  { id: 'PHP', name: '腓立比書', chapters: 4, testament: 'New' },
  { id: 'COL', name: '歌羅西書', chapters: 4, testament: 'New' },
  { id: '1TH', name: '帖撒羅尼迦前書', chapters: 5, testament: 'New' },
  { id: '2TH', name: '帖撒羅尼迦後書', chapters: 3, testament: 'New' },
  { id: '1TI', name: '提摩太前書', chapters: 6, testament: 'New' },
  { id: '2TI', name: '提摩太後書', chapters: 4, testament: 'New' },
  { id: 'TIT', name: '提多書', chapters: 3, testament: 'New' },
  { id: 'PHM', name: '腓利門書', chapters: 1, testament: 'New' },
  { id: 'HEB', name: '希伯來書', chapters: 13, testament: 'New' },
  { id: 'JAS', name: '雅各書', chapters: 5, testament: 'New' },
  { id: '1PE', name: '彼得前書', chapters: 5, testament: 'New' },
  { id: '2PE', name: '彼得後書', chapters: 3, testament: 'New' },
  { id: '1JO', name: '約翰一書', chapters: 5, testament: 'New' },
  { id: '2JO', name: '約翰二書', chapters: 1, testament: 'New' },
  { id: '3JO', name: '約翰三書', chapters: 1, testament: 'New' },
  { id: 'JUD', name: '猶大書', chapters: 1, testament: 'New' },
  { id: 'REV', name: '啟示錄', chapters: 22, testament: 'New' },
];
